name: Update XCFramework

# Triggered by XCFramework repo
on:
  repository_dispatch:
    types: [new_artifact]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - env:
          URL: ${{ github.event.client_payload.url }}
        run: echo $URL
