name: Update XCFramework

# Triggered by XCFramework repo
on: 
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to zipped XCFramework'     
        required: true
        type: string

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - env:
          URL: ${{ inputs.url }}
        run: echo $URL
        
      - name: Replace URL in Package.swift
        run: sed -i 's/\(url: "\).*\("\)/\1${{ inputs.url}}\2/g' Package.swift
        
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.14.1

